import * as fs from 'node:fs';
import * as path from 'node:path';
import type { CanonMsg, Conversation } from '../model.js';
import { readJsonl, walk, sha, uuid, appendJsonl, truncate, firstLine } from '../util.js';

export interface ClaudeParsed extends Conversation {
  side: 'claude';
  /** uuid of the last main-chain record; new records chain from here. */
  leafUuid: string | null;
  /** Fields copied onto records we write (version, userType, gitBranch...). */
  template: Record<string, unknown>;
  /** True when every message in the file was written by ai-sync. */
  allMirrored: boolean;
}

export interface ParseOpts { includeTools: 'summary' | 'none'; maxToolChars: number; }

/** Claude Code encodes a cwd into a project dir name by replacing every non-alphanumeric char with '-'. */
export const projectSlug = (cwd: string) => cwd.replace(/[^a-zA-Z0-9]/g, '-');

const NOISE_PREFIXES = [
  '<command-name>', '<command-message>', '<command-args>', '<local-command-stdout>',
  '<local-command-stderr>', '<local-command-caveat>', '[Request interrupted by user',
  'Caveat: The messages below were generated by the user while running local commands',
];

function cleanUserText(s: string): string {
  return s.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '').trim();
}

/** List candidate transcript files: <claudeDir>/projects/<slug>/<sessionId>.jsonl (subagent dirs excluded). */
export function listClaudeTranscripts(claudeDir: string): string[] {
  const root = path.join(claudeDir, 'projects');
  return walk(root, (p) => p.endsWith('.jsonl'), 1).filter((p) => path.dirname(path.dirname(p)) === root);
}

function renderTool(block: any, max: number): string {
  const input = typeof block.input === 'string' ? block.input : JSON.stringify(block.input ?? {});
  return `▸ ${block.name ?? 'tool'}: ${truncate(input, max)}`;
}

export function parseClaude(file: string, opts: ParseOpts): ClaudeParsed | null {
  let st: fs.Stats;
  try { st = fs.statSync(file); } catch { return null; }
  const lines = readJsonl(file);
  const messages: CanonMsg[] = [];
  let sessionId = path.basename(file, '.jsonl');
  let cwd = '';
  let leafUuid: string | null = null;
  let template: Record<string, unknown> = {};
  let customTitle = '', aiTitle = '', summary = '';
  let native = 0, mirrored = 0;

  for (const { obj: r } of lines) {
    if (!r || typeof r !== 'object') continue;
    switch (r.type) {
      case 'custom-title': if (r.customTitle) customTitle = String(r.customTitle); continue;
      case 'ai-title': if (r.aiTitle ?? r.title) aiTitle = String(r.aiTitle ?? r.title); continue;
      case 'summary': if (r.summary) summary = String(r.summary); continue;
    }
    if (r.isSidechain) continue;
    if (r.sessionId && typeof r.sessionId === 'string') sessionId = r.sessionId;
    if (!cwd && typeof r.cwd === 'string') cwd = r.cwd;
    if (typeof r.uuid === 'string' && (r.type === 'user' || r.type === 'assistant' || r.type === 'system' || r.type === 'attachment')) {
      leafUuid = r.uuid;
    }
    if (r.type !== 'user' && r.type !== 'assistant') continue;
    if (r.version) template = pickTemplate(r);
    if (r.isMeta || r.isCompactSummary || r.isVisibleInTranscriptOnly || r.isApiErrorMessage) continue;
    const content = r.message?.content;
    const ts = typeof r.timestamp === 'string' ? r.timestamp : '';
    const mirrorOf: string | undefined = r.aiSync?.id;
    const push = (m: Omit<CanonMsg, 'timestamp' | 'mirrorOf'>) => {
      messages.push({ ...m, timestamp: ts, ...(mirrorOf ? { mirrorOf } : {}) });
      mirrorOf ? mirrored++ : native++;
    };

    if (r.type === 'user') {
      const texts: string[] = [];
      if (typeof content === 'string') texts.push(content);
      else if (Array.isArray(content)) for (const b of content) if (b?.type === 'text' && typeof b.text === 'string') texts.push(b.text);
      const text = cleanUserText(texts.join('\n\n'));
      if (!text || NOISE_PREFIXES.some((p) => text.startsWith(p))) continue;
      push({ id: r.uuid, role: 'user', text, kind: 'text' });
    } else {
      if (!Array.isArray(content)) {
        if (typeof content === 'string' && content.trim()) push({ id: r.uuid, role: 'assistant', text: content, kind: 'text' });
        continue;
      }
      const text = content.filter((b: any) => b?.type === 'text' && b.text).map((b: any) => b.text).join('\n\n').trim();
      if (text) push({ id: r.uuid, role: 'assistant', text, kind: 'text' });
      if (opts.includeTools === 'summary') {
        const tools = content.filter((b: any) => b?.type === 'tool_use');
        if (tools.length) push({ id: `${r.uuid}#tool`, role: 'assistant', text: tools.map((b: any) => renderTool(b, opts.maxToolChars)).join('\n'), kind: 'tool' });
      }
    }
  }

  const firstUser = messages.find((m) => m.role === 'user')?.text ?? '';
  return {
    side: 'claude', path: file, id: sessionId, cwd,
    title: customTitle || aiTitle || summary || truncate(firstLine(firstUser), 80),
    messages, mtimeMs: st.mtimeMs, size: st.size, leafUuid, template,
    allMirrored: mirrored > 0 && native === 0,
  };
}

function pickTemplate(r: any): Record<string, unknown> {
  const t: Record<string, unknown> = {};
  for (const k of ['userType', 'version', 'gitBranch', 'entrypoint']) if (r[k] !== undefined) t[k] = r[k];
  return t;
}

// ---------------------------------------------------------------- writer

export interface ClaudeTarget { path: string; sessionId: string; cwd: string; leafUuid: string | null; template: Record<string, unknown>; model?: string; }

/** A record we are about to write, with its uuid known up front for the ledger's write-ahead entry. */
export interface PlannedClaudeRecord { uuid: string; msg: CanonMsg; }

export function planClaudeRecords(msgs: CanonMsg[]): PlannedClaudeRecord[] {
  return msgs.map((m) => ({ uuid: uuid(), msg: m }));
}

export function buildClaudeRecords(target: ClaudeTarget, planned: PlannedClaudeRecord[], src: 'codex'): any[] {
  let parent = target.leafUuid;
  const base = { userType: 'external', version: '0.0.0', ...target.template };
  return planned.map(({ uuid: u, msg }) => {
    const ts = msg.timestamp || new Date().toISOString();
    const common = {
      parentUuid: parent, isSidechain: false, ...base,
      cwd: target.cwd, sessionId: target.sessionId, uuid: u, timestamp: ts,
      aiSync: { v: 1, src, id: msg.id },
    };
    parent = u;
    if (msg.role === 'user') return { ...common, type: 'user', message: { role: 'user', content: msg.text } };
    return {
      ...common, type: 'assistant',
      message: {
        id: `msg_aisync_${sha(u, 20)}`, type: 'message', role: 'assistant', model: target.model ?? 'codex-via-ai-sync',
        content: [{ type: 'text', text: msg.text }], stop_reason: 'end_turn', stop_sequence: null,
        usage: { input_tokens: 0, output_tokens: 0, cache_creation_input_tokens: 0, cache_read_input_tokens: 0 },
      },
    };
  });
}

/** ClaudeTranscriptWriterPort: append mirrored messages to an existing transcript. */
export function appendClaude(target: ClaudeTarget, planned: PlannedClaudeRecord[]): void {
  appendJsonl(target.path, buildClaudeRecords(target, planned, 'codex'));
}

/** ClaudeCardWriterPort: write the title card so the session is recognisable in `claude --resume`. */
export function writeClaudeTitle(file: string, sessionId: string, title: string): void {
  appendJsonl(file, [{ type: 'custom-title', customTitle: title, sessionId }]);
}

/** Create a brand-new transcript for a Codex thread. Returns the target for subsequent appends. */
export function newClaudeTarget(claudeDir: string, cwd: string, template: Record<string, unknown>): ClaudeTarget {
  const sessionId = uuid();
  const dir = path.join(claudeDir, 'projects', projectSlug(cwd || '/'));
  return { path: path.join(dir, `${sessionId}.jsonl`), sessionId, cwd: cwd || '/', leafUuid: null, template };
}

/** Find any recent real record to copy version/userType from, so our records look like the installed Claude Code. */
export function findClaudeTemplate(files: string[]): Record<string, unknown> {
  const sorted = files.map((f) => { try { return [f, fs.statSync(f).mtimeMs] as const; } catch { return [f, 0] as const; } })
    .sort((a, b) => b[1] - a[1]).slice(0, 5);
  for (const [f] of sorted) {
    const lines = readJsonl(f);
    for (let i = lines.length - 1; i >= 0; i--) {
      const r = lines[i].obj;
      if ((r?.type === 'user' || r?.type === 'assistant') && r.version && !r.aiSync) return pickTemplate(r);
    }
  }
  return {};
}
